### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by jpmckinney** [comment]
@ColinMaudry Is this ready for review? extension.json is missing the `codelists` field for `permission.csv`.

**Comment by ColinMaudry** [comment]
Now it's ready for review :)

**Comment by jpmckinney** [comment]
Great work! Essentially perfect. I just had a few copy-edits.

**Comment by ColinMaudry** [comment]
I thought the CI checks checked the indenting. I'll configure my editor to set indenting to 2 spaces in JSON.

**Comment by jpmckinney** [comment]
CI only checks indenting in JSON files – I was editing the JSON snippet in the readme :)

**Pull request merged**
